### ISSUE TITLE
Cardlist style now appears to depend on {SETSTYLE} 

### ISSUE THREAD

**Issue by CaMer0n** [e107inc/bootstrap4#10]
Padding has returned where it should no longer be. 

![image](https://user-images.githubusercontent.com/2825679/59800610-ee78ef80-929b-11e9-858d-3e607eb49c0d.png)

**Comment by Jimmi08** [comment]
No,
it depends on this $options['list'], but I forgot that there can be the opposite case 

```
			if($style === 'listgroup' && empty($options['list']))
			{
				$style = 'cardmenu';
			}

 
			if($style === 'cardmenu' && $options['list'] == 1 )
			{
				$style = 'listgroup';
			} 
```

menuarea 1 is by default cardmenu, menuarea 2 is by default listgroup
it looks like good idea to test menus in both areas.  
theme should manage any case.  Not sure about it now. 

When option['list'] is 1?  I can't find where you set this for login_menu.

**Comment by CaMer0n** [comment]
@Jimmi08 The detection for `list` should be working properly now.

**Comment by Jimmi08** [comment]
It works, tested on topic view.
