### ISSUE TITLE
Carousel height in style.css is far too general.

### ISSUE THREAD

**Issue by CaMer0n** [e107inc/bootstrap4#11]
```
.carousel-item {
    height: 65vh;
```

![image](https://user-images.githubusercontent.com/2825679/59802318-a064eb80-929d-11e9-9972-a40df3a6b08e.png)

**Comment by Jimmi08** [comment]
Next reason why I wanted  inline style for featurebox. I will fix it. Export your menus to install/custom folder please. On mobile, no access to gitter.
