### ISSUE TITLE
weird behaviour with SETSTYLE in layout html

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/bootstrap4#13]
Can you use only styles default and main in layout html 
I tried to use nocaption or any other and CAPTION magic shortcode wasn't displayed.

**Comment by CaMer0n** [comment]
`{---CAPTION---}` is generated from a  `{SETSTYLE=default}` or `{SETSTYLE=main}`  tablerender() call - the first one encountered. 

ie. this is the intended behavior.

**Comment by Jimmi08** [comment]
So it's mean that you can use only those 2 styles for this?

**Comment by CaMer0n** [comment]
@Jimmi08 Correct.
