### ISSUE TITLE
Double breadcrumb on Forum pages

### ISSUE THREAD

**Issue by CaMer0n** [e107inc/bootstrap4#16]
@Jimmi08 I believe I already removed all the breadcrumbs from the forum templates before you moved those files into the `/temp` folder.  ;-)

**Comment by Jimmi08** [comment]
Only view topic template is used, others are from core...  temp is just for the list, I always use latest core version before moving

**Comment by CaMer0n** [comment]
@CaMer0n I edited the ones from core (in the theme folder) before you moved them to /temp. They should have all the breadcrumb shortcodes removed already. So moving them out of /temp should fix this issue.
