### ISSUE TITLE
Featurebox 

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/bootstrap4#9]
Supported only carousel

Solved for now by this:
![image](https://user-images.githubusercontent.com/5429548/59750260-d5157a80-927e-11e9-8881-55d251dd0af9.png)

Supported templates:

![image](https://user-images.githubusercontent.com/5429548/59750400-0c842700-927f-11e9-9f7d-644fc20ec08f.png)

Live example:
https://www.e107sk.com/demo/bootstrap4/

Height of carousel is defined in style.css 
Full page carousel: height: 100vh;
```
.carousel-item {
  height: 65vh;
  min-height: 300px;
  background: no-repeat center center scroll;
  -webkit-background-size: cover;
  -moz-background-size: cover;
  -o-background-size: cover;
  background-size: cover;
  background-color: #272B30;
  color: white;
}
```

**Needs to be done:
TABS**

**Comment by CaMer0n** [comment]
@Jimmi08 I don't understand the 'solution' ?

**Comment by Jimmi08** [comment]
With using IDs I could add new type without worrying about css.
